In [1]:
import yfinance as yf      # to download stock data
import pandas as pd       # for data handling
import numpy as np        # for calculations
import matplotlib.pyplot as plt   # for graphs
import seaborn as sns     # for advanced visuals

In [2]:
stocks = ['AAPL', 'MSFT', 'GOOGL', 'TSLA', 'AMZN']

In [3]:
data = yf.download(stocks, start="2022-01-01", end="2024-01-01")

[*********************100%***********************]  5 of 5 completed

In [6]:
data = yf.download(stocks, start="2022-01-01", end="2024-01-01")

data.columns

[*********************100%***********************]  5 of 5 completed

MultiIndex([( 'Close',  'AAPL'),
            ( 'Close',  'AMZN'),
            ( 'Close', 'GOOGL'),
            ( 'Close',  'MSFT'),
            ( 'Close',  'TSLA'),
            (  'High',  'AAPL'),
            (  'High',  'AMZN'),
            (  'High', 'GOOGL'),
            (  'High',  'MSFT'),
            (  'High',  'TSLA'),
            (   'Low',  'AAPL'),
            (   'Low',  'AMZN'),
            (   'Low', 'GOOGL'),
            (   'Low',  'MSFT'),
            (   'Low',  'TSLA'),
            (  'Open',  'AAPL'),
            (  'Open',  'AMZN'),
            (  'Open', 'GOOGL'),
            (  'Open',  'MSFT'),
            (  'Open',  'TSLA'),
            ('Volume',  'AAPL'),
            ('Volume',  'AMZN'),
            ('Volume', 'GOOGL'),
            ('Volume',  'MSFT'),
            ('Volume',  'TSLA')],
           names=['Price', 'Ticker'])

In [7]:
data = data['Close']

In [8]:
data.head()

Ticker            AAPL        AMZN       GOOGL        MSFT        TSLA
Date
2022-01-03  178.103668  170.404495  143.802963  323.160736  399.926666
2022-01-04  175.843231  167.522003  143.215836  317.619507  383.196655
2022-01-05  171.165848  164.356995  136.645615  305.426758  362.706665
2022-01-06  168.308548  163.253998  136.618347  303.013306  354.899994
2022-01-07  168.474854  162.554001  135.893829  303.167816  342.320007

In [9]:
data = data.dropna()

In [10]:
data.isnull().sum()

Ticker
AAPL     0
AMZN     0
GOOGL    0
MSFT     0
TSLA     0
dtype: int64

In [11]:
data.to_csv("clean_stock_data.csv")

In [12]:
data = yf.download(stocks, start="2022-01-01", end="2024-01-01", auto_adjust=True)

[*********************100%***********************]  5 of 5 completed

In [13]:

data = data['Close']

In [14]:
data = data.dropna()

In [15]:
data.head()

Ticker            AAPL        AMZN       GOOGL        MSFT        TSLA
Date
2022-01-03  178.103668  170.404495  143.802963  323.160736  399.926666
2022-01-04  175.843231  167.522003  143.215836  317.619507  383.196655
2022-01-05  171.165848  164.356995  136.645615  305.426758  362.706665
2022-01-06  168.308548  163.253998  136.618347  303.013306  354.899994
2022-01-07  168.474854  162.554001  135.893829  303.167816  342.320007